// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project. 
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc. 
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File". 
// You do not need to add suppressions to this file manually. 

#region Copyright
// Copyright (c) 2009, Kazi Manzur Rashid <kazimanzurrashid@gmail.com>.
// This source is subject to the Microsoft Public License. 
// See http://www.microsoft.com/opensource/licenses.mspx#Ms-PL. 
// All other rights reserved.
#endregion

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Portability", "CA1903:UseOnlyApiFromTargetedFramework", MessageId = "System.Web.Abstractions, Version=3.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Portability", "CA1903:UseOnlyApiFromTargetedFramework", MessageId = "System.Web.Routing, Version=3.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "type", Target = "System.Web.Mvc.Extensibility.TypeCatalog")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "System.Web.Mvc.Extensibility.TypeCatalog.#.ctor(System.Collections.Generic.IList`1<System.Reflection.Assembly>,System.Collections.Generic.IList`1<System.Predicate`1<System.Type>>,System.Collections.Generic.IList`1<System.Predicate`1<System.Type>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "System.Web.Mvc.Extensibility.TypeCatalog.#IncludeFilters")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "System.Web.Mvc.Extensibility.TypeCatalog.#ExcludeFilters")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "System.Web.Mvc.Extensibility.FilterRegistryItemBase.#.ctor(System.Collections.Generic.IEnumerable`1<System.Func`1<System.Web.Mvc.FilterAttribute>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "System.Web.Mvc.Extensibility.FilterRegistryItemBase.#Filters")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "System.Web.Mvc.Extensibility.FilterRegistryActionItem`1.#.ctor(System.Linq.Expressions.Expression`1<System.Action`1<!0>>,System.Collections.Generic.IEnumerable`1<System.Func`1<System.Web.Mvc.FilterAttribute>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "System.Web.Mvc.Extensibility.FilterRegistryControllerItem`1.#.ctor(System.Collections.Generic.IEnumerable`1<System.Func`1<System.Web.Mvc.FilterAttribute>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "System.Web.Mvc.Extensibility.IFilterRegistry.#Register`2(System.Collections.Generic.IEnumerable`1<System.Func`1<!!1>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1004:GenericMethodsShouldProvideTypeParameter", Scope = "member", Target = "System.Web.Mvc.Extensibility.IFilterRegistry.#Register`2(System.Collections.Generic.IEnumerable`1<System.Func`1<!!1>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "System.Web.Mvc.Extensibility.IFilterRegistry.#Register`2(System.Linq.Expressions.Expression`1<System.Action`1<!!0>>,System.Collections.Generic.IEnumerable`1<System.Func`1<!!1>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "System.Web.Mvc.Extensibility.FilterRegistry.#Register`2(System.Collections.Generic.IEnumerable`1<System.Func`1<!!1>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1004:GenericMethodsShouldProvideTypeParameter", Scope = "member", Target = "System.Web.Mvc.Extensibility.FilterRegistry.#Register`2(System.Collections.Generic.IEnumerable`1<System.Func`1<!!1>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "System.Web.Mvc.Extensibility.FilterRegistry.#Register`2(System.Linq.Expressions.Expression`1<System.Action`1<!!0>>,System.Collections.Generic.IEnumerable`1<System.Func`1<!!1>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1004:GenericMethodsShouldProvideTypeParameter", Scope = "member", Target = "System.Web.Mvc.Extensibility.FilterRegistryExtensions.#Register`1(System.Web.Mvc.Extensibility.IFilterRegistry,System.Web.Mvc.Extensibility.TypeCatalog)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1004:GenericMethodsShouldProvideTypeParameter", Scope = "member", Target = "System.Web.Mvc.Extensibility.FilterRegistryExtensions.#Register`2(System.Web.Mvc.Extensibility.IFilterRegistry)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1004:GenericMethodsShouldProvideTypeParameter", Scope = "member", Target = "System.Web.Mvc.Extensibility.FilterRegistryExtensions.#Register`2(System.Web.Mvc.Extensibility.IFilterRegistry,System.Action`1<!!1>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "System.Web.Mvc.Extensibility.FilterRegistryExtensions.#Register`2(System.Web.Mvc.Extensibility.IFilterRegistry,System.Linq.Expressions.Expression`1<System.Action`1<!!0>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1004:GenericMethodsShouldProvideTypeParameter", Scope = "member", Target = "System.Web.Mvc.Extensibility.FilterRegistryExtensions.#Register`2(System.Web.Mvc.Extensibility.IFilterRegistry,System.Linq.Expressions.Expression`1<System.Action`1<!!0>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "System.Web.Mvc.Extensibility.FilterRegistryExtensions.#Register`2(System.Web.Mvc.Extensibility.IFilterRegistry,System.Linq.Expressions.Expression`1<System.Action`1<!!0>>,System.Action`1<!!1>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1004:GenericMethodsShouldProvideTypeParameter", Scope = "member", Target = "System.Web.Mvc.Extensibility.FilterRegistryExtensions.#Register`2(System.Web.Mvc.Extensibility.IFilterRegistry,System.Web.Mvc.Extensibility.TypeCatalog)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1004:GenericMethodsShouldProvideTypeParameter", Scope = "member", Target = "System.Web.Mvc.Extensibility.FilterRegistryExtensions.#Register`3(System.Web.Mvc.Extensibility.IFilterRegistry)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "System.Web.Mvc.Extensibility.FilterRegistryExtensions.#Register`3(System.Web.Mvc.Extensibility.IFilterRegistry,System.Linq.Expressions.Expression`1<System.Action`1<!!0>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1004:GenericMethodsShouldProvideTypeParameter", Scope = "member", Target = "System.Web.Mvc.Extensibility.FilterRegistryExtensions.#Register`3(System.Web.Mvc.Extensibility.IFilterRegistry,System.Linq.Expressions.Expression`1<System.Action`1<!!0>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1004:GenericMethodsShouldProvideTypeParameter", Scope = "member", Target = "System.Web.Mvc.Extensibility.FilterRegistryExtensions.#Register`3(System.Web.Mvc.Extensibility.IFilterRegistry,System.Web.Mvc.Extensibility.TypeCatalog)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1004:GenericMethodsShouldProvideTypeParameter", Scope = "member", Target = "System.Web.Mvc.Extensibility.FilterRegistryExtensions.#Register`4(System.Web.Mvc.Extensibility.IFilterRegistry)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "System.Web.Mvc.Extensibility.FilterRegistryExtensions.#Register`4(System.Web.Mvc.Extensibility.IFilterRegistry,System.Linq.Expressions.Expression`1<System.Action`1<!!0>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1004:GenericMethodsShouldProvideTypeParameter", Scope = "member", Target = "System.Web.Mvc.Extensibility.FilterRegistryExtensions.#Register`4(System.Web.Mvc.Extensibility.IFilterRegistry,System.Linq.Expressions.Expression`1<System.Action`1<!!0>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1004:GenericMethodsShouldProvideTypeParameter", Scope = "member", Target = "System.Web.Mvc.Extensibility.FilterRegistryExtensions.#Register`4(System.Web.Mvc.Extensibility.IFilterRegistry,System.Web.Mvc.Extensibility.TypeCatalog)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1004:GenericMethodsShouldProvideTypeParameter", Scope = "member", Target = "System.Web.Mvc.Extensibility.FilterRegistryExtensions.#Register`5(System.Web.Mvc.Extensibility.IFilterRegistry)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "System.Web.Mvc.Extensibility.FilterRegistryExtensions.#Register`5(System.Web.Mvc.Extensibility.IFilterRegistry,System.Linq.Expressions.Expression`1<System.Action`1<!!0>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1004:GenericMethodsShouldProvideTypeParameter", Scope = "member", Target = "System.Web.Mvc.Extensibility.FilterRegistryExtensions.#Register`5(System.Web.Mvc.Extensibility.IFilterRegistry,System.Linq.Expressions.Expression`1<System.Action`1<!!0>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords", MessageId = "GetType", Scope = "member", Target = "System.Web.Mvc.Extensibility.IFluentSyntax.#GetType()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "System.Web.Mvc.Extensibility.IFluentSyntax.#GetType()")]
#if (!MVC1)
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Portability", "CA1903:UseOnlyApiFromTargetedFramework", MessageId = "System.ComponentModel.DataAnnotations, Version=3.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1040:AvoidEmptyInterfaces", Scope = "type", Target = "System.Web.Mvc.Extensibility.IModelMetadataAdditionalSetting")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "System.Web.Mvc.Extensibility.ModelMetadataRegistry.#Configurations")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "System.Web.Mvc.Extensibility.ModelMetadataConfigurationBase`1.#Append`2(System.Linq.Expressions.Expression`1<System.Func`2<!0,!!1>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1004:GenericMethodsShouldProvideTypeParameter", Scope = "member", Target = "System.Web.Mvc.Extensibility.ModelMetadataConfigurationBase`1.#Append`2(System.Linq.Expressions.Expression`1<System.Func`2<!0,!!1>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "System.Web.Mvc.Extensibility.ModelMetadataConfigurationBase`1.#Configure(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.Boolean>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "System.Web.Mvc.Extensibility.ModelMetadataConfigurationBase`1.#Configure(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.Byte>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "System.Web.Mvc.Extensibility.ModelMetadataConfigurationBase`1.#Configure(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.DateTime>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "System.Web.Mvc.Extensibility.ModelMetadataConfigurationBase`1.#Configure(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.Decimal>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "System.Web.Mvc.Extensibility.ModelMetadataConfigurationBase`1.#Configure(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.Double>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "System.Web.Mvc.Extensibility.ModelMetadataConfigurationBase`1.#Configure(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.Int16>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "System.Web.Mvc.Extensibility.ModelMetadataConfigurationBase`1.#Configure(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.Int32>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "System.Web.Mvc.Extensibility.ModelMetadataConfigurationBase`1.#Configure(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.Int64>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "System.Web.Mvc.Extensibility.ModelMetadataConfigurationBase`1.#Configure(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.Nullable`1<System.Boolean>>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "System.Web.Mvc.Extensibility.ModelMetadataConfigurationBase`1.#Configure(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.Nullable`1<System.Byte>>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "System.Web.Mvc.Extensibility.ModelMetadataConfigurationBase`1.#Configure(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.Nullable`1<System.DateTime>>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "System.Web.Mvc.Extensibility.ModelMetadataConfigurationBase`1.#Configure(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.Nullable`1<System.Decimal>>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "System.Web.Mvc.Extensibility.ModelMetadataConfigurationBase`1.#Configure(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.Nullable`1<System.Double>>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "System.Web.Mvc.Extensibility.ModelMetadataConfigurationBase`1.#Configure(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.Nullable`1<System.Int16>>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "System.Web.Mvc.Extensibility.ModelMetadataConfigurationBase`1.#Configure(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.Nullable`1<System.Int32>>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "System.Web.Mvc.Extensibility.ModelMetadataConfigurationBase`1.#Configure(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.Nullable`1<System.Int64>>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "System.Web.Mvc.Extensibility.ModelMetadataConfigurationBase`1.#Configure(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.Nullable`1<System.Single>>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "System.Web.Mvc.Extensibility.ModelMetadataConfigurationBase`1.#Configure(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.Single>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "System.Web.Mvc.Extensibility.ModelMetadataConfigurationBase`1.#Configure`1(System.Linq.Expressions.Expression`1<System.Func`2<!0,!!0>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "System.Web.Mvc.Extensibility.ModelMetadataConfigurationBase`1.#Configure(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.String>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "System.Web.Mvc.Extensibility.ValueTypeMetadataItemBuilderExtensions.#FormatAsCurrency(System.Web.Mvc.Extensibility.ValueTypeMetadataItemBuilder`1<System.Nullable`1<System.Decimal>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "System.Web.Mvc.Extensibility.ValueTypeMetadataItemBuilderExtensions.#FormatAsDateOnly(System.Web.Mvc.Extensibility.ValueTypeMetadataItemBuilder`1<System.Nullable`1<System.DateTime>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "System.Web.Mvc.Extensibility.ValueTypeMetadataItemBuilderExtensions.#FormatAsTimeOnly(System.Web.Mvc.Extensibility.ValueTypeMetadataItemBuilder`1<System.Nullable`1<System.DateTime>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope = "member", Target = "System.Web.Mvc.Extensibility.StringMetadataItemBuilder.#UrlErrorMessage")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope = "member", Target = "System.Web.Mvc.Extensibility.StringMetadataItemBuilder.#UrlExpression")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope = "member", Target = "System.Web.Mvc.Extensibility.StringMetadataItemBuilder.#UrlErrorMessageResourceName")]
#endif